[package]
name = "loxb"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = []
# default = ["print_code", "debug_trace_execution", "timings", "unsafe_stack"]

# These are my own features
timings = []
unsafe_stack = []

# These are somewhat faithful reproductions of clox's feature flags
debug_trace_execution = []
print_code = []
